// SPDX-License-Identifier: LGPL-3.0-or-later
#ifndef VISIONG_NPU_INTERNAL_TRACKING_ERROR_H
#define VISIONG_NPU_INTERNAL_TRACKING_ERROR_H

enum nn_error_e {
    NN_SUCCESS = 0,
    NN_LOAD_MODEL_FAIL = -1,
    NN_RKNN_INIT_FAIL = -2,
    NN_RKNN_QUERY_FAIL = -3,
    NN_RKNN_INPUT_SET_FAIL = -4,
    NN_RKNN_RUNTIME_ERROR = -5,
    NN_IO_NUM_NOT_MATCH = -6,
    NN_RKNN_OUTPUT_GET_FAIL = -7,
    NN_RKNN_INPUT_ATTR_ERROR = -8,
    NN_RKNN_OUTPUT_ATTR_ERROR = -9,
    NN_RKNN_MODEL_NOT_LOAD = -10,
};

#endif  // VISIONG_NPU_INTERNAL_TRACKING_ERROR_H
